package com;

public class Demo2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		try {
	
			int no =40/0;
		}
		catch(Exception e)//handle exception
		{
			System.out.println("Can't devide by 0");//custom message
		}
	}
}//but its doesnt show proper exception type
